steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp14repo/livegamequestionpusherimage', '.' ]

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp14repo/livegamequestionpusherimage'




